﻿﻿spring:
  application:
    name: tlias_web_management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 806717
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true